const STORE_TYPE = 'menu';

export const RECEIVE_MENU_LIST = `${STORE_TYPE}/RECEIVE_MENU_LIST`;
export const RECEIVE_MENU_LIST_SUCCESS = `${STORE_TYPE}/RECEIVE_MENU_LIST_SUCCESS`;
export const RECEIVE_MENU_LIST_FAILURE = `${STORE_TYPE}/RECEIVE_MENU_LIST_FAILURE`;
