const STORE_TYPE = 'cart';

export const ADD_TO_CART = `${STORE_TYPE}/ADD_TO_CART`;
export const REMOVE_FROM_CART = `${STORE_TYPE}/REMOVE_FROM_CART`;
export const REMOVE_ALL_FROM_CART = `${STORE_TYPE}/REMOVE_ALL_FROM_CART`;
export const SUBMIT_ORDER = `${STORE_TYPE}/SUBMIT_ORDER`;
