const pseudoServerResponse = [
  {
    section: 'pizza',
    id: '01',
    name: 'Pepperoni',
    description: 'Double pepperoni, mozzarella, marinara sauce, fresh basil',
    cost: '8.99',
    img_url: '/images/pepperoni.jpg',
  },
  {
    section: 'pizza',
    id: '02',
    name: 'Cheese',
    description: 'Mozzarella, marinara sauce, fresh basil',
    cost: '7.99',
    img_url: '/images/cheese.jpg',
  },
  {
    section: 'pizza',
    id: '03',
    name: 'Supreme',
    description: 'Pepperoni, fresh basil, mozzarella, italian sausage, bacon, mushrooms, red onions, black olives, green peppers, marinara sauce',
    cost: '11.99',
    img_url: '/images/supreme.jpg',
  },
  {
    section: 'pizza',
    id: '04',
    name: 'Meat Pizza',
    description: 'Pepperoni, ham, italian sausage, mozzarella, bacon, marinara sauce, fresh basil',
    cost: '11.99',
    img_url: '/images/meat.jpg',
  },
  {
    section: 'pizza',
    id: '05',
    name: 'Hawaiian',
    description: 'Ham, fresh pineapple, mozzarella, marinara sauce, fresh basil',
    cost: '10.99',
    img_url: '/images/hawaiian.jpg',
  },
  {
    section: 'pizza',
    id: '06',
    name: 'Sausage',
    description: 'Double italian sausage, mozzarella, marinara sauce, fresh basil',
    cost: '9.99',
    img_url: '/images/sausage.jpg',
  },
  {
    section: 'pizza',
    id: '07',
    name: 'Veggie',
    description: 'Green peppers, cherry tomatoes, mozzarella, ricotta, fresh parsley, mushrooms, black olives, red onions',
    cost: '10.99',
    img_url: '/images/veggie.jpg',
  },
  {
    section: 'pizza',
    id: '08',
    name: 'Chicken Club',
    description: 'Grilled chicken, cherry tomatoes, ricotta, fresh parsley, mozzarella, bacon, red onions',
    cost: '8.99',
    img_url: '/images/chicken.jpg',
  },
  {
    section: 'drinks',
    id: '101',
    name: 'Sprite',
    description: '20 fl.oz',
    cost: '1.79',
    img_url: '/images/sprite.png',
  },
  {
    section: 'drinks',
    id: '102',
    name: 'Coca Cola',
    description: '20 fl.oz',
    cost: '1.79',
    img_url: '/images/coke.png',
  },
  {
    section: 'drinks',
    id: '103',
    name: 'Fanta',
    description: '20 fl.oz',
    cost: '1.79',
    img_url: '/images/fanta.png',
  },
];

export default pseudoServerResponse;